version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
      - ORACLE_INITSQL=/opt/oracle/scripts/setup/init.sql
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
      - ./db-init-scripts/init.sql:/opt/oracle/scripts/setup/init.sql
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@localhost:1521/ORCLCDB as sysdba", "SELECT 1 FROM DUAL"]
      interval: 30s
      timeout: 10s
      retries: 5

  tomcat:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps
    environment:
      - DB_URL=jdbc:oracle:thin:@oracle-db:1521:ORCLPDB1
      - DB_USER=library
      - DB_PASSWORD=mypassword
    depends_on:
      - oracle-db

volumes:
  oracle-data:
    driver: local
  oracle-backup:
    driver: local