DROP USER library CASCADE;
-- Crear un nuevo usuario y contraseña
CREATE USER library IDENTIFIED BY mypassword;

-- Otorgar permisos al nuevo usuario
GRANT ALL PRIVILEGES TO library;

-- Crear las tablas en el esquema del nuevo usuario
CREATE TABLE library.client (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    second_last_name VARCHAR2(50),
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(50) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE library.employee (
    id VARCHAR2(10) NOT NULL,
    first_name VARCHAR2(50) NOT NULL,
    middle_name VARCHAR2(50),
    last_name VARCHAR2(50) NOT NULL,
    second_last_name VARCHAR2(50),
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    birth_date DATE NOT NULL,
    position VARCHAR2(50) NOT NULL,
    library_code VARCHAR2(20),
    PRIMARY KEY (id)
);

-- Insertar datos de ejemplo en la tabla client
INSERT INTO library.client (first_name, last_name, password, email)
VALUES ('John', 'Doe', 'password123', 'john.doe@example.com');

-- Insertar datos de ejemplo en la tabla employee
INSERT INTO library.employee (id, first_name, last_name, password, email, birth_date, position, library_code)
VALUES ('7-822-1692', 'Jane', 'Doe', 'password123', 'jane.doe@example.com', TO_DATE('1985-05-15', 'YYYY-MM-DD'), 'Manager', 'LIB001');

