-- Crear la tabla client
CREATE TABLE client (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    middle_name VARCHAR2(50),
    last_name VARCHAR2(50) NOT NULL,
    second_last_name VARCHAR2(50),
    password VARCHAR2(255) NOT NULL,  -- Incrementar el tamaño para mayor seguridad
    email VARCHAR2(50) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

-- Crear la tabla employee
CREATE TABLE employee (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    middle_name VARCHAR2(50),
    last_name VARCHAR2(50) NOT NULL,
    second_last_name VARCHAR2(50),
    password VARCHAR2(255) NOT NULL,  -- Incrementar el tamaño para mayor seguridad
    email VARCHAR2(100) NOT NULL UNIQUE,
    birth_date DATE NOT NULL,
    position VARCHAR2(50) NOT NULL,
    library_code VARCHAR2(20),
    PRIMARY KEY (id)
);

-- Insertar datos de ejemplo en la tabla client
INSERT INTO client (first_name, middle_name, last_name, second_last_name, password, email)
VALUES ('John', 'A.', 'Doe', 'Smith', 'password123', 'john.doe@example.com');

-- Insertar datos de ejemplo en la tabla employee
INSERT INTO employee (first_name, middle_name, last_name, second_last_name, password, email, birth_date, position, library_code)
VALUES ('Jane', 'B.', 'Doe', 'Johnson', 'password123', 'jane.doe@example.com', TO_DATE('1985-05-15', 'YYYY-MM-DD'), 'Manager', 'LIB001');

--Drop all tables
--DROP TABLE client;
--DROP TABLE employee;